(* Rational arguments are lifted using their zeros and poles. *)
ClearAll[rsCompile, rsRationalQ, rsFiniteQ, rsPhases, rsLogs, rsValue,
  rsWalk, rsSurface, rsSheetOffsets, rsExplorer, rsL];
rsFiniteQ[v_] := NumberQ[N[v]] && FreeQ[N[v], Indeterminate | DirectedInfinity];
rsRationalQ[g_, z_] := Module[{t = Together[g]},
  PolynomialQ[Numerator[t], z] && PolynomialQ[Denominator[t], z]];
rsCompile[input_, z_] := Module[{bases, form, roots, rows, t, factors, all,
    coeff, powers, poles, heads},
  heads = DeleteDuplicates[Cases[input, e_ /; !AtomQ[e] :> Head[e], {0, Infinity}]];
  If[Complement[heads, {Plus, Times, Power, Log, Sin, Cos, Tan, Sinh, Cosh, Tanh, Rational, Complex}] =!= {},
    Return[Failure["Function", <|"Message" -> "Supported: arithmetic, constant powers of rational arguments, Log, Exp, Sin/Cos/Tan and hyperbolic functions."|>]]];
  bases = DeleteDuplicates[Cases[input,
    Log[g_] :> g, {0, Infinity}]];
  bases = DeleteDuplicates@Join[bases, Cases[input,
    Power[g_, p_] /; !IntegerQ[p] && !FreeQ[g, z] :> g, {0, Infinity}]];
  If[!And @@ (rsRationalQ[#, z] & /@ bases),
    Return[Failure["Argument", <|"Message" -> "Log and noninteger powers require rational functions of z."|>]]];
  If[!And @@ (rsFiniteQ /@ Cases[input,
      Power[g_, p_] /; !IntegerQ[p] && !FreeQ[g, z] :> p, {0, Infinity}]),
    Return[Failure["Exponent", <|"Message" -> "Exponents must be numeric constants (exact expressions are allowed)."|>]]];
  form = input /. {Log[g_] :> rsL[g],
    Power[g_, p_] /; !IntegerQ[p] && !FreeQ[g, z] :> Exp[p rsL[g]]};
  If[!FreeQ[form, Log],
    Return[Failure["Form", <|"Message" -> "Unsupported nested or variable-exponent expression."|>]]];
  (* Include the denominator of the full expression when it is rational. *)
  poles = Join[If[rsRationalQ[input, z], {Denominator[Together[input]]}, {}],
    Cases[input, Power[g_, p_Integer] /; p < 0 && !FreeQ[g, z] && rsRationalQ[g, z] :> g, {0, Infinity}]];
  all = DeleteDuplicates@Join[bases, poles];
  roots = {}; rows = {};
  Do[
    t = Together[g];
    factors = Join[
      ({First[#], Last[#]} & /@ Rest[FactorList[Numerator[t]]]),
      ({First[#], -Last[#]} & /@ Rest[FactorList[Denominator[t]]])];
    powers = Flatten[Table[
      ({#, f[[2]]} & /@ (z /. NSolve[f[[1]] == 0, z])), {f, factors}], 1];
    (* FactorList multiplicities and NSolve roots together encode divisors. *)
    AppendTo[rows, powers]; roots = Join[roots, First /@ powers], {g, all}];
  roots = DeleteDuplicates[roots, Abs[#1 - #2] < 10^-9 &];
  coeff = Table[Table[Total[Last /@ Select[row, Abs[First[#] - rt] < 10^-8 &]],
      {rt, roots}], {row, Take[rows, Length[bases]]}];
  If[!And @@ (rsFiniteQ /@ roots), Return[Failure["Roots", <|"Message" -> "Could not resolve finite zeros/poles."|>]]];
  <|"Expression" -> input, "Variable" -> z, "Bases" -> bases,
    "Roots" -> roots, "Multiplicities" -> coeff, "Form" -> form|>
];
rsPhases[m_, zz_] := Arg[zz - #] & /@ m["Roots"];
rsLogs[m_, zz_, ph_, offset_] := MapThread[
  Log[Abs[N[#1 /. m["Variable"] -> zz]]] + I (#2.ph + #3) &,
  {m["Bases"], m["Multiplicities"], offset}];
rsValue[m_, zz_, ph_, offset_] := Quiet[N[m["Form"] /.
    Thread[(rsL /@ m["Bases"]) -> rsLogs[m, zz, ph, offset]] /.
    m["Variable"] -> zz]];

(* Enumerate monodromy generated by loops around actual roots. Rational
   powers form a finite orbit; logarithms and irrational powers do not. *)
rsSheetOffsets[m_, zz_, ph_, offset_, height_, maxSheets_] := Module[
  {n = Length[offset], exponents, logs, finite, period, gens, queue,
   seen, cursor = 1, state, child, radius, candidates, visible,
   anchor = Im[rsValue[m, zz, ph, offset]], margin, complete},
  If[n == 0 || m["Roots"] === {},
    Return[<|"Offsets" -> {offset}, "Complete" -> True|>]];
  logs = Cases[m["Expression"], Log[g_] /; !FreeQ[g, m["Variable"]], {0, Infinity}];
  exponents = Cases[m["Expression"],
    Power[g_, p_] /; !IntegerQ[p] && !FreeQ[g, m["Variable"]] :> p, {0, Infinity}];
  finite = logs === {} && AllTrue[exponents, Head[#] === Rational &];
  period = If[finite && exponents =!= {}, Apply[LCM, Denominator /@ exponents], 1];
  gens = DeleteDuplicates[Transpose[m["Multiplicities"]]];
  gens = DeleteCases[gens, ConstantArray[0, n]];
  If[gens === {}, Return[<|"Offsets" -> {offset}, "Complete" -> True|>]];
  radius = If[finite, Infinity, Ceiling[height/(2 Pi)] + 3];
  queue = {ConstantArray[0, n]}; seen = queue;
  While[cursor <= Length[queue] && Length[seen] < 800,
    state = queue[[cursor++]];
    Do[
      child = state + sign gen;
      If[finite, child = Mod[child, period]];
      If[(!finite && Max[Abs[child]] > radius) || MemberQ[seen, child], Continue[]];
      AppendTo[seen, child]; AppendTo[queue, child],
      {gen, gens}, {sign, {-1, 1}}]
  ];
  candidates = offset + 2 Pi # & /@ seen;
  margin = Pi Max[Total[Abs[#]] & /@ m["Multiplicities"]];
  visible = If[finite, candidates,
    Select[candidates, With[{v = Im[rsValue[m, zz, ph, #]]},
      rsFiniteQ[v] && Abs[v] <= height + margin] &]];
  visible = DeleteDuplicates[visible, Norm[#1 - #2] < 10^-8 &];
  visible = SortBy[visible, Abs[Im[rsValue[m, zz, ph, #]] - anchor] &];
  complete = finite && cursor > Length[queue] && Length[visible] <= maxSheets;
  <|"Offsets" -> Take[visible, UpTo[maxSheets]], "Complete" -> complete|>
];

(* The path is linear in polar coordinates, not a straight complex chord. *)
rsWalk[m_, state_, target_, offset_] := Module[
  {r = state[[1]], th = state[[2]], ph = state[[3]], pts = {}, msg = "",
   step, rr, tt, zz, next, val, distance, span, dt, dr, h, count = 0},
  While[Abs[target[[1]] - r] + Abs[target[[2]] - th] > 10^-12,
    zz = r Exp[I th]; distance = If[m["Roots"] === {}, Infinity,
      Min[Abs[zz - m["Roots"]]]];
    If[distance < 10^-7 || ++count > 100000,
      msg = "Stopped near a zero/pole or at the step budget; go around it or use smaller moves."; Break[]];
    dr = target[[1]] - r; dt = target[[2]] - th;
    span = Abs[dr] + Max[r, target[[1]]] Abs[dt];
    h = Min[1., .05/Max[span, 10^-30], .2 distance/Max[span, 10^-30],
      .04/Max[Abs[dt], 10^-30]];
    rr = r + h dr; tt = th + h dt; next = rr Exp[I tt];
    step = Arg[(next - #)/(zz - #)] & /@ m["Roots"];
    val = rsValue[m, next, ph + step, offset];
    If[!rsFiniteQ[val], msg = "Nonfinite function value; move stopped."; Break[]];
    r = rr; th = tt; ph += step;
    AppendTo[pts, {Re[next], Im[next], Im[val]}];
  ]; {{r, th, ph}, pts, msg}
];

(* Anchor each chart at the moving point and join its cut to any displayed
   chart with the same lifted value. Clip the vertical view to a finite box. *)
rsSurface[m_, zz_, ph_, offset_, bound_, charts_, marks_, height_] := Module[
  {xs, ys, xy, phases, good, values, triangles, ids, n, polygons,
   i, j, a, b, c, d, valid, rootMarks, localRadius, meshN,
   bridgeTriangles, lifted},
  localRadius = Min[.02 bound, If[m["Roots"] === {}, bound, Min[Abs[zz - m["Roots"]]]/4]];
  meshN = Max[16, Round[44 Sqrt[3/Max[3, Length[charts]]]]];
  xs = Sort@DeleteDuplicates@Join[N@Subdivide[-bound, bound, meshN], Re[zz] + {-localRadius, 0, localRadius}];
  ys = Sort@DeleteDuplicates@Join[N@Subdivide[-bound, bound, meshN], Im[zz] + {-localRadius, 0, localRadius}];
  xy = Flatten[Table[x + I y, {x, xs}, {y, ys}]]; n = Length[ys];
  good = Function[q, m["Roots"] === {} || Min[Abs[q - m["Roots"]]] > 10^-7] /@ xy;
  phases = Function[q, ph + (Arg[(q - #)/(zz - #)] & /@ m["Roots"])] /@ xy;
  triangles = Flatten[Table[a = (i - 1) n + j; b = a + n; c = b + 1; d = a + 1;
      {{a, b, c}, {a, c, d}}, {i, Length[xs] - 1}, {j, n - 1}], 2];
  valid[tri_] := And @@ good[[tri]] && (m["Roots"] === {} ||
      Max[Abs[Flatten[Differences[Append[phases[[tri]], phases[[First[tri]]]]]]]] < Pi);
  bridgeTriangles = Select[triangles, And @@ good[[#]] && !valid[#] &];
  triangles = Select[triangles, valid];
  lifted[tri_, off_] := Module[{anchor = xy[[First[tri]]], localPh, vv},
    localPh = Table[phases[[First[tri]]] +
      (Arg[(xy[[k]] - #)/(anchor - #)] & /@ m["Roots"]), {k, tri}];
    vv = MapThread[rsValue[m, #1, #2, off] &, {xy[[tri]], localPh}];
    If[!And @@ (rsFiniteQ /@ vv) ||
      !And @@ MapThread[
        Function[{k, v}, AnyTrue[charts,
          Abs[v - rsValue[m, xy[[k]], phases[[k]], #]] < 10^-7 &]],
        {tri, vv}], Nothing,
      Polygon[MapThread[{Re[#1], Im[#1], Im[#2]} &, {xy[[tri]], vv}]]]];
  polygons = Table[
    values = MapThread[If[#3, rsValue[m, #1, #2, off], Indeterminate] &, {xy, phases, good}];
    ids = Select[triangles, And @@ (rsFiniteQ /@ values[[#]]) &];
    {Directive[If[off === offset, LightBlue, LightGray], Opacity[.52]],
      GraphicsComplex[MapThread[{Re[#1], Im[#1], If[rsFiniteQ[#2], Im[#2], 0.]} &, {xy, values}],
        Polygon[ids]],
      lifted[#, off] & /@ bridgeTriangles}, {off, charts}];
  rootMarks = If[marks, {Red, PointSize[.013],
      Tooltip[Point[{Re[#], Im[#], 0}], Row[{"zero / pole: ", #}]] & /@ m["Roots"]}, {}];
  Graphics3D[{EdgeForm[], polygons, rootMarks},
    PlotRange -> {{-bound, bound}, {-bound, bound}, {-height, height}},
    PlotRangeClipping -> True]
];

rsExplorer[] := DynamicModule[
  {text = "((z+1)(z-1)(z-I))^(1/3)", model, r = 1.6, theta = 0.,
   center = 0., rmax = 4., height = 12., maxSheets = 36,
   visibleHeight = 12., displayBound = 5., sheetInfo = <|"Offsets" -> {}, "Complete" -> True|>,
   ph = {}, offset = {}, trail = {}, surf = Graphics3D[{}],
   notice = "", allSheets = True, marks = True, dragging = False,
   apply, rebuild, move, table},
  Column[{
    Row[{"f(z)  ", InputField[Dynamic[text], String, FieldSize -> 54], Spacer[8],
      Button["Apply / reset", apply[], Method -> "Queued"]}],
    Grid[{{
      Pane[Column[{
        Row[{Style["z = r Exp[I theta]", Bold], Spacer[12],
          Dynamic[Style[Row[{Length[sheetInfo["Offsets"]], " sheets",
            Which[!TrueQ[allSheets], " (selected)",
              TrueQ[sheetInfo["Complete"]], " (all)", True, " (sampled)"]}],
            10, Gray], TrackedSymbols :> {sheetInfo, allSheets}]}],
        Row[{"r  ", InputField[Dynamic[r, Function[v, move[v, theta]]], Expression, FieldSize -> 9],
          "  max ", InputField[Dynamic[rmax, (If[rsFiniteQ[#] && TrueQ[# >= r], rmax = N[#]; rebuild[]] &)], Expression, FieldSize -> 6]}],
        Dynamic[Slider[Dynamic[r, Function[v, move[v, theta]]], {.01, rmax}, ContinuousAction -> False, ImageSize -> 265], TrackedSymbols :> {rmax}],
        Row[{"theta  ", InputField[Dynamic[theta, Function[v, move[r, v]; center = theta]], Expression, FieldSize -> 14]}],
        Dynamic[Slider[Dynamic[theta, {None,
            Function[v, dragging = True; move[r, v, False]],
            Function[v, move[r, v, True]; dragging = False]}],
          {center - 2 Pi, center + 2 Pi}, ContinuousAction -> True,
          ImageSize -> 265], TrackedSymbols :> {center}],
        Row[{Button["-2 Pi", move[r, theta - 2 Pi]; center = theta, Method -> "Queued"],
          Button["Center", center = theta], Button["+2 Pi", move[r, theta + 2 Pi]; center = theta, Method -> "Queued"]}],
        Row[{Button["Clear trail", trail = {Last[trail]}], Spacer[8],
          Button["Reset sheet", apply[], Method -> "Queued"]}],
        Row[{"Im w box ", InputField[Dynamic[height,
          Function[v, If[rsFiniteQ[v] && TrueQ[v > 0], height = N[v]; rebuild[]]]],
          Expression, FieldSize -> 6], "  sheet limit ",
          InputField[Dynamic[maxSheets,
            Function[v, If[IntegerQ[v] && v > 0, maxSheets = v; rebuild[]]]],
            Expression, FieldSize -> 5]}],
        Row[{Checkbox[Dynamic[allSheets, Function[v, allSheets = v; rebuild[]]]], " All sheets in box", Spacer[8],
          Checkbox[Dynamic[marks, Function[v, marks = v; rebuild[]]]], " Zeros/poles"}],
        Dynamic[Row[{"w = ", NumberForm[rsValue[model, r Exp[I theta], ph, offset], 6]}], TrackedSymbols :> {r, theta, ph, model}, UpdateInterval -> .5],
        Pane[Dynamic[table[], TrackedSymbols :> {r, theta, ph, model}, UpdateInterval -> .5], {300, 190}, Scrollbars -> Automatic],
        Pane[Dynamic[Style[notice, Darker[Red]]], {300, 48}, Scrollbars -> Automatic]
      }, Spacings -> .6], {310, 460}],
      Dynamic[Show[surf, Graphics3D[{{Orange, Thick, Line[trail]}, {Red, PointSize[.02], Point[Last[trail]]}}],
        PlotRange -> {{-displayBound, displayBound}, {-displayBound, displayBound},
          {-visibleHeight, visibleHeight}}, PlotRangeClipping -> True,
        Axes -> True, AxesLabel -> {"Re z", "Im z", "Im w"},
        BoxRatios -> {1, 1, .8}, SphericalRegion -> True, ImageSize -> {530, 460}],
        TrackedSymbols :> {surf, trail, displayBound, visibleHeight}, SynchronousUpdating -> False]
    }}, Alignment -> Top, Spacings -> {0, 0}],
    Style["Enter Wolfram Language with variable z; examples: ((z-1)/(z+1))^(2/3), ((z-I)/(z+2))^Sqrt[2], Log[(z-1)/(z+1)], Exp[z].", 10]
  }, BaseStyle -> {FontFamily -> "Arial", FontSize -> 11}]
, Initialization :> (  rebuild[] := (
      displayBound = 1.25 Max[rmax, r, If[trail === {}, 0, Max[Norm /@ trail[[All, 1 ;; 2]]]]];
      visibleHeight = Max[height, If[trail === {}, 0, Max[Abs[trail[[All, 3]]]] + 2]];
      sheetInfo = If[allSheets,
        rsSheetOffsets[model, r Exp[I theta], ph, offset, visibleHeight, maxSheets],
        <|"Offsets" -> {offset}, "Complete" -> True|>];
      surf = rsSurface[model, r Exp[I theta], ph, offset, displayBound,
        sheetInfo["Offsets"], marks, visibleHeight]);
  apply[] := Module[{expr, mm, zz, pp, oo, vv},
    expr = Quiet@Check[ToExpression[text, InputForm], $Failed];
    If[expr === $Failed, notice = "Invalid Wolfram Language expression."; Return[]];
    mm = Quiet@Check[rsCompile[expr, Global`z], $Failed];
    If[FailureQ[mm] || mm === $Failed, notice = If[FailureQ[mm], mm["Message"], "Cannot analyze expression."]; Return[]];
    zz = r Exp[I theta]; pp = rsPhases[mm, zz];
    If[AnyTrue[mm["Roots"], Abs[zz - #] < 10^-7 &], notice = "Move z away from a zero/pole first."; Return[]];
    oo = MapThread[Arg[N[#1 /. Global`z -> zz]] - #2.pp &, {mm["Bases"], mm["Multiplicities"]}];
    vv = rsValue[mm, zz, pp, oo];
    If[!rsFiniteQ[vv], notice = "Expression is not finite/numeric at current z, or contains unsupported functions."; Return[]];
    model = mm; ph = pp; offset = oo; trail = {{Re[zz], Im[zz], Im[vv]}};
    center = theta; notice = ""; rebuild[]];
  move[nr_, nt_, refresh_: True] := Module[{out},
    If[!rsFiniteQ[nr] || !rsFiniteQ[nt] || !TrueQ[Im[N[nr]] == 0 && Im[N[nt]] == 0 && nr > 0],
      notice = "Use real r > 0 and real theta."; Return[]];
    out = rsWalk[model, {r, theta, ph}, N[{nr, nt}], offset];
    {r, theta, ph} = out[[1]]; trail = Join[trail, out[[2]]]; notice = out[[3]];
    rmax = Max[rmax, 1.1 r];
    If[TrueQ[refresh], center = theta; rebuild[]]];
  table[] := Module[{zz = r Exp[I theta], rows, args},
    rows = {{"z", NumberForm[Arg[zz]/Pi, {8, 3}], NumberForm[theta/Pi, {8, 3}]}};
    rows = Join[rows, MapThread[{Row[{"z - (", #1, ")"}],
        NumberForm[Arg[zz - #1]/Pi, {8, 3}], NumberForm[#2/Pi, {8, 3}]} &, {model["Roots"], ph}]];
    args = Im[rsLogs[model, zz, ph, offset]];
    rows = Join[rows, MapThread[{ToString[#1, InputForm],
        NumberForm[Arg[N[#1 /. Global`z -> zz]]/Pi, {8, 3}], NumberForm[#2/Pi, {8, 3}]} &, {model["Bases"], args}]];
    Grid[Prepend[rows, {"Argument", "Arg / Pi", "continuous / Pi"}], Alignment -> Left,
      Background -> {None, {LightGray, None}}, Dividers -> All, BaseStyle -> 10]];
  apply[])];




